### ISSUE TITLE
Сюда бы github actions добавить с бейджиком

### ISSUE THREAD

**Issue by mokevnin** [hexlet-components/java-servlet-gradle#2]

**Comment by corsicanec82** [comment]
Добавил:
- сборку github action ([коммит](https://github.com/hexlet-components/java-servlet-gradle/commit/3e91950f194054dac17ed80f1b54439270b7cfd7))
- тесты с отчетом о покрытии ([коммит](https://github.com/hexlet-components/java-servlet-gradle/commit/77538bb8fa9d21e06538420f0d7c376737c13c2e))
- все бейджи, в т.ч codeclimate, плюс покрытие тестами ([коммит](https://github.com/hexlet-components/java-servlet-gradle/commit/3978e26a058b63865e70ab55354d5866a0f7bd25))
- линтер + немного причесал реализацию (местами упростил, убрал использование var) ([коммит](https://github.com/hexlet-components/java-servlet-gradle/commit/1e9d2ba2f82702d6da988443369d7181b999c67f))
